### ISSUE TITLE
"-v" doesn't show version number

### ISSUE THREAD

**Issue by nmancus1** [nmancus1/parseva-math#36]
fix cli so that -v shows version number.

```
➜  parseva-math git:(fix-cli) java -jar --enable-preview target/parseva-math-0.1-SNAPSHOT-jar-with-dependencies.jar -v
Exception in thread "main" picocli.CommandLine$UnmatchedArgumentException: Unknown option: '-v'
        at picocli.CommandLine$Interpreter.validateConstraints(CommandLine.java:13143)
        at picocli.CommandLine$Interpreter.parse(CommandLine.java:13095)
        at picocli.CommandLine$Interpreter.parse(CommandLine.java:13041)
        at picocli.CommandLine$Interpreter.parse(CommandLine.java:12942)
        at picocli.CommandLine.parseArgs(CommandLine.java:1478)
        at parsevamath.tools.Main.main(Main.java:67)

```

**Comment by nmancus1** [comment]
Fix is merged.
