### ISSUE TITLE
parseva-math should not throw exception in interactive mode, just error message

### ISSUE THREAD

**Issue by nmancus1** [nmancus1/parseva-math#39]
```
> pow(2,2)
line 1:5 token recognition error at: ','
line 1:6 extraneous input '2' expecting ')'
2021-01-09 12:13:08 [main] parsevamath.tools.MathAstBuilder.visitFuncExpr()
INFO: Failed to get 'java.lang.Math' method 'pow'
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "mathMethod" is null
        at parsevamath.tools.EvaluateExpressionVisitor.visit(EvaluateExpressionVisitor.java:104)
        at parsevamath.tools.EvaluateExpressionVisitor.visit(EvaluateExpressionVisitor.java:142)
        at parsevamath.tools.Main.evaluate(Main.java:122)
        at parsevamath.tools.Main.runInteractive(Main.java:101)
        at parsevamath.tools.Main.main(Main.java:71)


```
It would be better to identify error, yet stay in interactive mode

**Comment by nmancus1** [comment]
Fix is merged.
